# Generated by Django 2.2 on 2020-10-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_delete_ordergoods'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsInfo',
        ),
    ]
