# Generated by Django 2.2 on 2020-10-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_delete_goodsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=2000)),
                ('goods_price', models.IntegerField(default=0)),
                ('goods_img', models.ImageField(upload_to='goods')),
                ('goods_desc', models.CharField(max_length=2000)),
                ('goods_cag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory')),
            ],
        ),
    ]
